RESULT = pumpkin-git
SOURCES = \
  strutils.mli strutils.ml \
  ioutils.mli ioutils.ml \
  retrieve.mli retrieve.ml \
  main.ml

THREADS = yes
PACKS = core str

OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
